CREATE TABLE `market_regimes` (
	`run_id` text PRIMARY KEY NOT NULL,
	`market_date` text NOT NULL,
	`methodology_version` text NOT NULL,
	`regime_label` text NOT NULL,
	`regime_score` real NOT NULL,
	`benchmark_close` real NOT NULL,
	`benchmark_sma50` real NOT NULL,
	`benchmark_sma200` real NOT NULL,
	`benchmark_sma50_slope20` real NOT NULL,
	`benchmark_sma200_slope20` real NOT NULL,
	`benchmark_return20` real NOT NULL,
	`benchmark_realized_volatility20` real NOT NULL,
	`breadth_above20` real NOT NULL,
	`breadth_above50` real NOT NULL,
	`breadth_above200` real NOT NULL,
	`breadth_momentum` real NOT NULL,
	`new_high_rate` real NOT NULL,
	`new_low_rate` real NOT NULL,
	`volume_participation_rate` real NOT NULL,
	`sector_positive_rate` real NOT NULL,
	`benchmark_trend_score` real NOT NULL,
	`breadth_score` real NOT NULL,
	`sector_breadth_score` real NOT NULL,
	`participation_score` real NOT NULL,
	`volatility_score` real NOT NULL,
	`minimum_quant_score` integer NOT NULL,
	`max_equity_exposure` real NOT NULL,
	`new_position_size_multiplier` real NOT NULL,
	`minimum_cash_allocation` real NOT NULL,
	`max_new_entries` integer NOT NULL,
	`trend_weight_multiplier` real NOT NULL,
	`explanation_json` text NOT NULL,
	`row_hash` text NOT NULL,
	`created_at` text NOT NULL,
	FOREIGN KEY (`run_id`) REFERENCES `quant_runs`(`id`) ON UPDATE no action ON DELETE cascade
);
--> statement-breakpoint
CREATE UNIQUE INDEX `market_regimes_date_methodology_uq` ON `market_regimes` (`market_date`,`methodology_version`);--> statement-breakpoint
CREATE INDEX `market_regimes_label_date_idx` ON `market_regimes` (`regime_label`,`market_date`);--> statement-breakpoint
CREATE TABLE `research_regime_stats` (
	`regime_label` text NOT NULL,
	`horizon` integer NOT NULL,
	`sample_size` integer NOT NULL,
	`average_return` real NOT NULL,
	`median_return` real NOT NULL,
	`win_rate` real NOT NULL,
	`average_mae` real NOT NULL,
	`average_mfe` real NOT NULL,
	`standard_error` real,
	`confidence_low` real,
	`confidence_high` real,
	`profit_factor` real,
	`first_signal_date` text NOT NULL,
	`last_exit_date` text NOT NULL,
	`updated_at` text NOT NULL,
	PRIMARY KEY(`regime_label`, `horizon`)
);
