CREATE TABLE `portfolio_allocations` (
	`run_id` text NOT NULL,
	`market_date` text NOT NULL,
	`methodology_version` text NOT NULL,
	`symbol` text NOT NULL,
	`trade_id` text NOT NULL,
	`trade_state` text NOT NULL,
	`sector` text NOT NULL,
	`quant_score` real NOT NULL,
	`last_close` real NOT NULL,
	`atr_pct` real NOT NULL,
	`stop_distance_pct` real NOT NULL,
	`average_traded_value_20` real NOT NULL,
	`score_multiplier` real NOT NULL,
	`volatility_multiplier` real NOT NULL,
	`liquidity_multiplier` real NOT NULL,
	`correlation_multiplier` real NOT NULL,
	`target_weight` real NOT NULL,
	`risk_budget` real NOT NULL,
	`risk_contribution` real NOT NULL,
	`volatility_contribution` real,
	`beta` real,
	`correlation_cluster` text NOT NULL,
	`sector_cap_applied` integer NOT NULL,
	`flags_json` text NOT NULL,
	`row_hash` text NOT NULL,
	`created_at` text NOT NULL,
	PRIMARY KEY(`run_id`, `symbol`),
	FOREIGN KEY (`run_id`) REFERENCES `quant_runs`(`id`) ON UPDATE no action ON DELETE cascade,
	FOREIGN KEY (`symbol`) REFERENCES `instruments`(`symbol`) ON UPDATE no action ON DELETE no action
);
--> statement-breakpoint
CREATE INDEX `portfolio_allocations_run_risk_idx` ON `portfolio_allocations` (`run_id`,`risk_contribution`);--> statement-breakpoint
CREATE INDEX `portfolio_allocations_run_sector_idx` ON `portfolio_allocations` (`run_id`,`sector`);--> statement-breakpoint
CREATE TABLE `portfolio_publications` (
	`run_id` text PRIMARY KEY NOT NULL,
	`status` text DEFAULT 'PENDING' NOT NULL,
	`methodology_version` text NOT NULL,
	`expected_allocations` integer NOT NULL,
	`received_allocations` integer DEFAULT 0 NOT NULL,
	`allocation_payload_hash` text NOT NULL,
	`summary_hash` text NOT NULL,
	`summary_received` integer DEFAULT false NOT NULL,
	`regime_label` text,
	`max_equity_exposure` real,
	`minimum_cash_allocation` real,
	`max_portfolio_risk` real,
	`position_cap` real NOT NULL,
	`sector_cap` real NOT NULL,
	`correlation_threshold` real NOT NULL,
	`position_count` integer,
	`capital_deployed` real,
	`cash_allocation` real,
	`portfolio_risk` real,
	`largest_position` real,
	`top5_concentration` real,
	`portfolio_quant_score` real,
	`portfolio_beta` real,
	`expected_volatility` real,
	`sector_exposure_json` text,
	`correlation_clusters_json` text,
	`automatic_execution` integer DEFAULT false NOT NULL,
	`started_at` text NOT NULL,
	`committed_at` text,
	FOREIGN KEY (`run_id`) REFERENCES `quant_runs`(`id`) ON UPDATE no action ON DELETE cascade
);
--> statement-breakpoint
CREATE INDEX `portfolio_publications_status_idx` ON `portfolio_publications` (`status`);